package de.materna.dmn.tester.enums;

public enum RestErrorCode {
	BAD_JWT, EMAIL_TAKEN, MISSING_RIGHTS, NOT_CREATED, NOT_FOUND, NOT_LOGGED_IN, NOT_MODIFIED, PASSWORD_WRONG,
	USERNAME_NOT_FOUND, USERNAME_TAKEN
}
