apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: declab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: declab
  serviceName: declab-0
  template:
    metadata:
      labels:
        app: declab
    spec:
      containers:
        - name: declab
          image: maternase/declab:2.10.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: declab-storage
              mountPath: /opt/jboss/wildfly/standalone/data/dmn
          readinessProbe:
            httpGet:
              path: /api/workspaces
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: declab-storage
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 2G
---
apiVersion: v1
kind: Service
metadata:
  name: declab
spec:
  selector:
    statefulset.kubernetes.io/pod-name: declab-0
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080